export const SELECT_CARD = "SELECT_CARD";
export const DESELECT_CARD = "DESELECT_CARD";
export const TURN_CARD = "TURN_CARD";

export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS";

export const UPDATE_AMOUNT_OF_CARDS = "UPDATE_AMOUNT_OF_CARDS";
export const TOGGLE_ZERO_CARD = "TOGGLE_ZERO_CARD";
export const TOGGLE_HALFY_CARD = "TOGGLE_HALFY_CARD";
export const TOGGLE_INFINITY_CARD = "TOGGLE_INFINITY_CARD";
export const TOGGLE_T_SHIRT_SIZING_CARDS = "TOGGLE_T_SHIRT_SIZING_CARDS";

export const UPDATE_BACKGROUND_COLOR = "UPDATE_BACKGROUND_COLOR";

export const UPDATE_CARD_BACK_BACKGROUND_COLOR =
  "UPDATE_CARD_BACK_BACKGROUND_COLOR";
export const UPDATE_CARD_FRONT_BACKGROUND_COLOR =
  "UPDATE_CARD_FRONT_BACKGROUND_COLOR";
export const UPDATE_CARD_FRONT_FONT_COLOR = "UPDATE_CARD_FRONT_FONT_COLOR";
